application: drop2drink
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /(hydrants|cisterns)/[0-9]+
  script: hydrant.py